name: Bundle Maven Release

on: [workflow_dispatch]

jobs:
  bundle:
    uses: Forsakringskassan/.github/.github/workflows/bundle-maven-quarkus-release.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

  publish-maven:
    needs: bundle
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-tags: "true"
          fetch-depth: "0"
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 17
      - name: Deploy to GitHub Packages
        env:
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
        run: mvn -B -DskipTests deploy
